### ISSUE TITLE
[Issue]Time is stagnant

### ISSUE THREAD

**Issue by SeanChengN** [Aang23/RealSerene#1] opened 2018-09-13 06:53 UTC
[Problem Reproduction]
1. Set "realDayTime=true" then create a new world (Or existing world).
2. Time is running normally.
![1](https://user-images.githubusercontent.com/20624068/45470683-490b7b00-b761-11e8-81b5-015ce6efb77f.png)
3. Set "realDayTime=false" in-game or restart game, the result is the same anyway.
4. Time is stagnant.
![2](https://user-images.githubusercontent.com/20624068/45470758-8c65e980-b761-11e8-91b9-06716c049ab7.png)
5. Set "realDayTime=true" again.
6. Time is running normally again.
![3](https://user-images.githubusercontent.com/20624068/45470823-b7e8d400-b761-11e8-964c-e09273b25157.png)

Even if I delete this mod and restart game, the time is still stagnant. Except create a new world without this mod.

**Comment by Aang23** [comment] 2018-09-16 10:08
Can you check the doDaylightCycle gamerule in each case you have spoke about ?
I think I know what the issue is.

**Comment by SeanChengN** [comment] 2018-09-16 12:08
> Can you check the doDaylightCycle gamerule in each case you have spoke about ?
> I think I know what the issue is.

Whether I enable or disable realDayTime, doDaylightCycle is always false, Except delete RealSerene.

**Comment by Aang23** [comment] 2018-09-16 17:52
So I know what the issue is. This will be fixed soon, in the next release.

**Closed as completed** 2018-09-19 04:47 UTC
Labels: bug, Fixed

**Comment by hendersont2** [comment] 2018-10-30 02:01
Just had the same issue. Will switching "realDayTime" on and off get it working again?

**Comment by Aang23** [comment] 2018-11-09 16:38
Yes, that a gamerule issue...
